version: "3" 

services:
  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    container_name: db
    env_file:
      - .env
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
        
  pytest:
    image: harvestingtest:latest
    env_file:
      - .env
    build:
      context: .
    command: poetry run pytest -s --junitxml=pytest.xml --cov=datagovharvester | tee pytest-coverage.txt
    volumes:
      - ./.env:/app/.env
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pg_data: