version: "3" 

services:
  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    env_file:
      - .env
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  pg_data: