"""empty message

Revision ID: 88ee7681dd5e
Revises: d54743615c25
Create Date: 2024-03-14 14:31:37.633336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ee7681dd5e'
down_revision = 'd54743615c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_record',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('ckan_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_metadata', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_org', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('maintainer', sa.String(), nullable=True),
    sa.Column('maintainer_email', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['harvest_job.id'], ),
    sa.ForeignKeyConstraint(['owner_org'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvest_record')
    op.drop_table('organization')
    # ### end Alembic commands ###
