"""tables creation

Revision ID: d54743615c25
Revises: 
Create Date: 2024-03-13 14:08:31.783144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd54743615c25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_source',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notification_emails', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('schema_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('harvest_source_id', sa.String(), nullable=True),
    sa.Column('harvest_source_name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_job',
    sa.Column('harvest_source_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_deleted', sa.Integer(), nullable=True),
    sa.Column('records_errored', sa.Integer(), nullable=True),
    sa.Column('records_ignored', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.ForeignKeyConstraint(['harvest_source_id'], ['harvest_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_error',
    sa.Column('harvest_job_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('record_reported_id', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.ForeignKeyConstraint(['harvest_job_id'], ['harvest_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvest_error')
    op.drop_table('harvest_job')
    op.drop_table('harvest_source')
    # ### end Alembic commands ###
